'use client';

import React, { useState, useEffect, useRef, useCallback } from 'react';
import styles from './presentation.module.css';
// Language content is defined inline below

const BNBChainPresentation = () => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [touchStartX, setTouchStartX] = useState(0);
  const [lang, setLang] = useState<'en'|'es'|'pt'>('en');

  const t = {
    en: {
      s1_title: 'DISCOVERING BNB CHAIN',
      s1_sub: 'Your gateway to the Web3 world',
      s1_role: 'LatAm Community Lead, BNB Chain',
      s2_heading: 'Not just one chain. An ecosystem.',
      s2_c1t: 'BNB Smart Chain (BSC)', s2_c1d: 'The main layer. EVM compatible, high speed, low cost.',
      s2_c2t: 'opBNB', s2_c2d: 'Layer 2. Massive transactions at near-zero cost.',
      s2_c3t: 'BNB Greenfield', s2_c3d: 'Decentralized data storage.',
      s2_c4t: 'AvengerDAO', s2_c4d: "The ecosystem's security system.",
      s2_foot: 'ALL CONNECTED. ALL COMPATIBLE.',
      s3_heading: 'The numbers speak for themselves.',
      s3_l1: 'BLOCK TIME', s3_s1: 'vs 12s on Ethereum',
      s3_l2: 'AVG GAS', s3_s2: 'per transaction',
      s3_l3: 'TVL DeFi', s3_s3: 'in DeFi protocols',
      s3_l4: 'ACTIVE USERS', s3_s4: 'monthly',
      s3_l5: 'DAILY TXS', s3_s5: 'on BSC',
      s3_l6: 'EVM COMPATIBLE', s3_s6: 'same Solidity',
      s4_heading: 'For the Developer',
      s4_b1: 'No new learning curve',
      s4_b2: 'Fees 100x lower than Ethereum mainnet',
      s4_b3: 'Access to 32M+ users from day 1',
      s4_stmt: 'If it compiles on Ethereum, it deploys on BNB Chain.',
      s4_sub: 'Same Solidity. Same Foundry. Just change the RPC.',
      s5_heading: 'The chain with the most autonomous agent activity.',
      s5_hl: '35% of current network activity is generated by autonomous agents via ERC-8183.',
      s5_c1t: 'MCP + BNB Chain Skills', s5_c1d: 'Connect any LLM to BNB Chain contracts in minutes.',
      s5_c2t: 'BNBAgent SDK (ERC-8183)', s5_c2d: 'Register agents onchain with identity, work and payment.',
      s5_c3t: 'ERC-8004', s5_c3d: 'Decentralized registry. Your agent has an address, reputation and history.',
      s6_heading: 'Concrete ideas for the AI + Web3 track',
      s6_c1t: 'Trading & Agents', s6_c1d: 'Bot that monitors liquidity on PancakeSwap and rebalances portfolios with risk limits.',
      s6_c2t: 'UX for Regular Users', s6_c2d: "Telegram bot: user writes 'Invest 50 USDC in BNB' and the MCP agent handles everything.",
      s6_c3t: 'Smart DCA', s6_c3d: 'Agent that stops if volatility is high and skips if gas is expensive.',
      s7_heading: "BNB Chain is not just infrastructure. It's community.",
      s7_c1t: 'MVB (Most Valuable Builder)', s7_c1d: 'Incubation, funding and access to ecosystem investors.',
      s7_c2t: 'YZi Labs EASY Residency', s7_c2d: 'For early-stage projects with real traction.',
      s7_c3t: 'Hackathons', s7_c3d: 'BNB Chain co-sponsors global and regional hackathons.',
      s7_c4t: 'Institutional Partners', s7_c4d: 'BlackRock, CMB International, Franklin Templeton.',
      s8_title: "What's already happening in LatAm",
      s9_pill: 'CRECIMIENTO POP UP', s9_title: 'Technical workshop for founders in LatAm.',
      s9_stat: '+20 founders participated.', s9_sub: '5+ in active conversations with our BD team.',
      s10_pill: 'VENDIMIATECH HACKATHON', s10_title: 'Main partners of the AI + Web3 track.',
      s10_stat: '+10 projects. 3 winners.', s10_sub: '1st place is already talking with our AI and Agents team.',
      s11_pill: 'BINANCE UNIVERSITY TOUR — UTN', s11_title: 'Spreading the word at LatAm universities.',
      s11_stat: '+100 students.', s11_sub: 'The next generation of builders in the region.',
      s12_heading: 'Everything you need to get started today.',
      s12_c1t: 'Testnet Faucet', s12_c1d: 'Free gas for testnet',
      s12_c2t: 'BscScan Testnet', s12_c2d: 'Transaction explorer',
      s12_c3t: 'Official Docs', s12_c3d: 'docs.bnbchain.org',
      s12_c4t: 'BNB Chain Skills (MCP)', s12_c4d: 'Connect your agent to BNB Chain',
      s12_c5t: 'BNBAgent SDK', s12_c5d: 'github.com/bnb-chain/bnbagent-sdk',
      s12_c6t: 'ChainList RPC', s12_c6d: 'BSC Testnet RPC',
      s13_sub: 'BUILD WEB3 WITH BNB CHAIN',
      s13_qr: 'Follow us on X',
    },
    es: {
      s1_title: 'DESCUBRIENDO BNB CHAIN',
      s1_sub: 'Tu puerta de entrada al mundo Web3',
      s1_role: 'LatAm Community Lead, BNB Chain',
      s2_heading: 'No es una sola cadena. Es un ecosistema.',
      s2_c1t: 'BNB Smart Chain (BSC)', s2_c1d: 'La capa principal. EVM compatible, alta velocidad, bajo costo.',
      s2_c2t: 'opBNB', s2_c2d: 'La capa 2. Transacciones masivas a costo casi cero.',
      s2_c3t: 'BNB Greenfield', s2_c3d: 'Almacenamiento descentralizado de datos.',
      s2_c4t: 'AvengerDAO', s2_c4d: 'El sistema de seguridad del ecosistema.',
      s2_foot: 'TODO CONECTADO. TODO COMPATIBLE.',
      s3_heading: 'Los números hablan solos.',
      s3_l1: 'BLOCK TIME', s3_s1: 'vs 12s en Ethereum',
      s3_l2: 'GAS PROMEDIO', s3_s2: 'por transacción',
      s3_l3: 'TVL DeFi', s3_s3: 'en protocolos DeFi',
      s3_l4: 'USUARIOS ACTIVOS', s3_s4: 'mensuales',
      s3_l5: 'TX DIARIAS', s3_s5: 'en BSC',
      s3_l6: 'EVM COMPATIBLE', s3_s6: 'mismo Solidity',
      s4_heading: 'Para el Developer',
      s4_b1: 'Sin curva de aprendizaje nueva',
      s4_b2: 'Fees 100x más bajos que mainnet Ethereum',
      s4_b3: 'Acceso a 32M+ usuarios desde el día 1',
      s4_stmt: 'Si compila en Ethereum, se deploya en BNB Chain.',
      s4_sub: 'Mismo Solidity. Mismo Foundry. Solo cambiás el RPC.',
      s5_heading: 'La cadena con más actividad de agentes autónomos.',
      s5_hl: 'El 35% de la actividad actual de la red es generada por agentes autónomos vía ERC-8183.',
      s5_c1t: 'MCP + BNB Chain Skills', s5_c1d: 'Conectá cualquier LLM a contratos de BNB Chain en minutos.',
      s5_c2t: 'BNBAgent SDK (ERC-8183)', s5_c2d: 'Registrá agentes onchain con identidad, trabajo y pago.',
      s5_c3t: 'ERC-8004', s5_c3d: 'Registro descentralizado. Tu agente tiene dirección, reputación e historial.',
      s6_heading: 'Ideas concretas para el track de IA + Web3',
      s6_c1t: 'Trading & Agentes', s6_c1d: 'Bot que monitorea liquidez en PancakeSwap y rebalancea portafolios con límites de riesgo.',
      s6_c2t: 'UX para Usuarios Normales', s6_c2d: "Bot en Telegram: el usuario escribe 'Invertí 50 USDC en BNB' y el agente MCP arma todo.",
      s6_c3t: 'DCA Inteligente', s6_c3d: 'Agente que frena si la volatilidad es alta y saltea si el gas está caro.',
      s7_heading: 'BNB Chain no solo es infraestructura. Es comunidad.',
      s7_c1t: 'MVB (Most Valuable Builder)', s7_c1d: 'Incubación, funding y acceso a inversores del ecosistema.',
      s7_c2t: 'YZi Labs EASY Residency', s7_c2d: 'Para proyectos early-stage con tracción real.',
      s7_c3t: 'Hackathons', s7_c3d: 'BNB Chain co-patrocina hackathons globales y regionales.',
      s7_c4t: 'Socios Institucionales', s7_c4d: 'BlackRock, CMB International, Franklin Templeton.',
      s8_title: 'Lo que ya está pasando en LatAm',
      s9_pill: 'CRECIMIENTO POP UP', s9_title: 'Workshop técnico para founders en LatAm.',
      s9_stat: '+20 founders participaron.', s9_sub: '5+ en conversaciones activas con nuestro equipo de BD.',
      s10_pill: 'VENDIMIATECH HACKATHON', s10_title: 'Partners principales del track IA + Web3.',
      s10_stat: '+10 proyectos. 3 ganadores.', s10_sub: 'El 1er lugar ya conversa con nuestro equipo de IA y Agentes.',
      s11_pill: 'BINANCE UNIVERSITY TOUR — UTN', s11_title: 'Spreading the word en universidades de LatAm.',
      s11_stat: '+100 estudiantes.', s11_sub: 'La próxima generación de builders de la región.',
      s12_heading: 'Todo lo que necesitás para arrancar hoy.',
      s12_c1t: 'Testnet Faucet', s12_c1d: 'Gas gratis para testnet',
      s12_c2t: 'BscScan Testnet', s12_c2d: 'Explorador de transacciones',
      s12_c3t: 'Docs Oficiales', s12_c3d: 'docs.bnbchain.org',
      s12_c4t: 'BNB Chain Skills (MCP)', s12_c4d: 'Conectá tu agente a BNB Chain',
      s12_c5t: 'BNBAgent SDK', s12_c5d: 'github.com/bnb-chain/bnbagent-sdk',
      s12_c6t: 'ChainList RPC', s12_c6d: 'BSC Testnet RPC',
      s13_sub: 'CONSTRUYE WEB3 CON BNB CHAIN',
      s13_qr: 'Seguinos en X',
    },
    pt: {
      s1_title: 'DESCOBRINDO A BNB CHAIN',
      s1_sub: 'Sua porta de entrada para o mundo Web3',
      s1_role: 'LatAm Community Lead, BNB Chain',
      s2_heading: 'Não é só uma rede. É um ecossistema.',
      s2_c1t: 'BNB Smart Chain (BSC)', s2_c1d: 'A camada principal. Compatível com EVM, alta velocidade, baixo custo.',
      s2_c2t: 'opBNB', s2_c2d: 'Camada 2. Transações massivas a custo quase zero.',
      s2_c3t: 'BNB Greenfield', s2_c3d: 'Armazenamento descentralizado de dados.',
      s2_c4t: 'AvengerDAO', s2_c4d: 'O sistema de segurança do ecossistema.',
      s2_foot: 'TUDO CONECTADO. TUDO COMPATÍVEL.',
      s3_heading: 'Os números falam por si.',
      s3_l1: 'BLOCK TIME', s3_s1: 'vs 12s no Ethereum',
      s3_l2: 'GÁS MÉDIO', s3_s2: 'por transação',
      s3_l3: 'TVL DeFi', s3_s3: 'em protocolos DeFi',
      s3_l4: 'USUÁRIOS ATIVOS', s3_s4: 'mensais',
      s3_l5: 'TXs DIÁRIAS', s3_s5: 'na BSC',
      s3_l6: 'EVM COMPATÍVEL', s3_s6: 'mesmo Solidity',
      s4_heading: 'Para o Developer',
      s4_b1: 'Sem nova curva de aprendizado',
      s4_b2: 'Fees 100x mais baixas que mainnet Ethereum',
      s4_b3: 'Acesso a 32M+ usuários desde o dia 1',
      s4_stmt: 'Se compila no Ethereum, faz deploy na BNB Chain.',
      s4_sub: 'Mesmo Solidity. Mesmo Foundry. Só muda o RPC.',
      s5_heading: 'A rede com mais atividade de agentes autônomos.',
      s5_hl: '35% da atividade atual da rede é gerada por agentes autônomos via ERC-8183.',
      s5_c1t: 'MCP + BNB Chain Skills', s5_c1d: 'Conecte qualquer LLM a contratos da BNB Chain em minutos.',
      s5_c2t: 'BNBAgent SDK (ERC-8183)', s5_c2d: 'Registre agentes onchain com identidade, trabalho e pagamento.',
      s5_c3t: 'ERC-8004', s5_c3d: 'Registro descentralizado. Seu agente tem endereço, reputação e histórico.',
      s6_heading: 'Ideias concretas para o track de IA + Web3',
      s6_c1t: 'Trading & Agentes', s6_c1d: 'Bot que monitora liquidez na PancakeSwap e rebalancea portfólios com limites de risco.',
      s6_c2t: 'UX para Usuários Normais', s6_c2d: "Bot no Telegram: usuário escreve 'Investi 50 USDC em BNB' e o agente MCP resolve tudo.",
      s6_c3t: 'DCA Inteligente', s6_c3d: 'Agente que para se a volatilidade for alta e pula se o gas estiver caro.',
      s7_heading: 'BNB Chain não é só infraestrutura. É comunidade.',
      s7_c1t: 'MVB (Most Valuable Builder)', s7_c1d: 'Incubação, funding e acesso a investidores do ecossistema.',
      s7_c2t: 'YZi Labs EASY Residency', s7_c2d: 'Para projetos early-stage com tração real.',
      s7_c3t: 'Hackathons', s7_c3d: 'BNB Chain co-patrocina hackathons globais e regionais.',
      s7_c4t: 'Parceiros Institucionais', s7_c4d: 'BlackRock, CMB International, Franklin Templeton.',
      s8_title: 'O que já está acontecendo na LatAm',
      s9_pill: 'CRECIMIENTO POP UP', s9_title: 'Workshop técnico para founders na LatAm.',
      s9_stat: '+20 founders participaram.', s9_sub: '5+ em conversas ativas com nosso time de BD.',
      s10_pill: 'VENDIMIATECH HACKATHON', s10_title: 'Parceiros principais do track IA + Web3.',
      s10_stat: '+10 projetos. 3 vencedores.', s10_sub: 'O 1º lugar já conversa com nosso time de IA e Agentes.',
      s11_pill: 'BINANCE UNIVERSITY TOUR — UTN', s11_title: 'Espalhando a palavra nas universidades da LatAm.',
      s11_stat: '+100 estudantes.', s11_sub: 'A próxima geração de builders da região.',
      s12_heading: 'Tudo que você precisa para começar hoje.',
      s12_c1t: 'Testnet Faucet', s12_c1d: 'Gas grátis para testnet',
      s12_c2t: 'BscScan Testnet', s12_c2d: 'Explorador de transações',
      s12_c3t: 'Docs Oficiais', s12_c3d: 'docs.bnbchain.org',
      s12_c4t: 'BNB Chain Skills (MCP)', s12_c4d: 'Conecte seu agente à BNB Chain',
      s12_c5t: 'BNBAgent SDK', s12_c5d: 'github.com/bnb-chain/bnbagent-sdk',
      s12_c6t: 'ChainList RPC', s12_c6d: 'BSC Testnet RPC',
      s13_sub: 'CONSTRUA WEB3 COM BNB CHAIN',
      s13_qr: 'Siga-nos no X',
    },
  };

  const c = t[lang];

  const totalSlides = 13;

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'ArrowRight' || e.code === 'Space') {
      e.preventDefault();
      setCurrentSlide((prev) => (prev + 1) % totalSlides);
    } else if (e.key === 'ArrowLeft') {
      e.preventDefault();
      setCurrentSlide((prev) => (prev - 1 + totalSlides) % totalSlides);
    }
  };

  const handleTouchStart = (e: React.TouchEvent) => {
    setTouchStartX(e.touches[0].clientX);
  };

  const handleTouchEnd = (e: React.TouchEvent) => {
    const touchEndX = e.changedTouches[0].clientX;
    const deltaX = touchEndX - touchStartX;

    if (Math.abs(deltaX) > 50) {
      if (deltaX < 0) {
        setCurrentSlide((prev) => (prev + 1) % totalSlides);
      } else {
        setCurrentSlide((prev) => (prev - 1 + totalSlides) % totalSlides);
      }
    }
  };

  useEffect(() => {
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const progressPercentage = ((currentSlide + 1) / totalSlides) * 100;

  // --- Count-up animation for slide 3 ---
  const STATS = [
    { target: 0.45, decimals: 2, prefix: '~',  suffix: 's'  },
    { target: 0.03, decimals: 2, prefix: '<$', suffix: ''   },
    { target: 11.8, decimals: 1, prefix: '$',  suffix: 'B'  },
    { target: 32,   decimals: 0, prefix: '',   suffix: 'M+' },
    { target: 4.6,  decimals: 1, prefix: '',   suffix: 'M+' },
    { target: 100,  decimals: 0, prefix: '',   suffix: '%'  },
  ];

  const [countValues, setCountValues] = useState(STATS.map(() => 0));
  const rafRef = useRef<number | null>(null);

  const easeOutQuart = (x: number) => 1 - Math.pow(1 - x, 4);

  const runCountUp = useCallback(() => {
    if (rafRef.current !== null) cancelAnimationFrame(rafRef.current);
    setCountValues(STATS.map(() => 0));
    const duration = 1200;
    const start = performance.now();

    const tick = (now: number) => {
      const elapsed = now - start;
      const progress = Math.min(elapsed / duration, 1);
      const eased = easeOutQuart(progress);

      setCountValues(STATS.map((s) => s.target * eased));

      if (progress < 1) {
        rafRef.current = requestAnimationFrame(tick);
      } else {
        setCountValues(STATS.map((s) => s.target));
        rafRef.current = null;
      }
    };

    rafRef.current = requestAnimationFrame(tick);
  }, []);

  useEffect(() => {
    if (currentSlide === 2) {
      runCountUp();
    }
    return () => {
      if (rafRef.current !== null) cancelAnimationFrame(rafRef.current);
    };
  }, [currentSlide, runCountUp]);

  const formatStat = (index: number) => {
    const { target, decimals, prefix, suffix } = STATS[index];
    const raw = countValues[index];
    const display = raw >= target ? target.toFixed(decimals) : raw.toFixed(decimals);
    return `${prefix}${display}${suffix}`;
  };

  // Logo SVG component
  const Logo = () => (
    <svg width="110" height="auto" viewBox="0 0 319 56" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet">
      <g clipPath="url(#a)">
        <mask id="b" style={{ maskType: 'luminance' }} maskUnits="userSpaceOnUse" x="0" y="0" width="319" height="56">
          <path d="M319 0H0v56h319V0Z" fill="#fff" />
        </mask>
        <g mask="url(#b)">
          <path d="M9.342 8.578 24.203 0l14.86 8.578-5.463 3.168L24.203 6.338l-9.397 5.408-5.464-3.168ZM39.063 19.395l-5.463-3.169-9.397 5.409-9.397-5.409-5.464 3.169v6.337l9.397 5.409v10.817l5.463 3.169 5.464-3.169V25.733l9.397-5.409v-6.929ZM39.063 36.55v-6.337l-5.463 3.169v6.337l5.463-3.169Zm3.88 2.24-9.397 5.409v6.337l14.86-8.577V24.804l-5.463 3.169V38.79ZM37.479 13.986l5.464 3.169v6.337l5.463-3.169v-6.337l-5.463-3.169-5.464 3.169ZM18.74 46.494v6.337L24.203 56l5.463-3.169v-6.337l-5.463 3.169-5.463-3.169ZM9.342 36.55l5.464 3.169v-6.337l-5.464-3.169V36.55Zm9.397-22.564 5.464 3.169 5.463-3.169-5.463-3.169-5.464 3.169ZM5.463 17.155l5.464-3.169-5.464-3.168L0 13.986v6.337l5.463 3.169v-6.337ZM5.463 27.973 0 24.804V41.96l14.86 8.577v-6.337L5.463 38.79V27.973Z" fill="#fff" />
          <path d="M91.478 35.143v-.089c0-4.185-2.226-6.278-5.832-7.658 2.226-1.246 4.096-3.205 4.096-6.723v-.089c0-4.897-3.918-8.058-10.285-8.058H64.987v31.166H79.813c7.035 0 11.665-2.85 11.665-8.549Zm-8.548-13.312c0 2.315-1.914 3.295-4.942 3.295h-6.322v-6.59h6.767c2.894 0 4.497 1.158 4.497 3.206v.089Zm1.736 12.466c0 2.315-1.825 3.384-4.853 3.384h-8.147v-6.857h8.236c3.517 0 5.075 1.291 5.075 3.384v.089h-.311ZM125.256 43.692V12.526h-6.767v19.189L103.886 12.526h-6.323v31.166h6.768V23.879l15.093 19.813h5.832ZM159.674 35.143v-.089c0-4.185-2.226-6.278-5.833-7.658 2.226-1.246 3.896-3.205 3.896-6.723v-.089c0-4.897-3.918-8.058-10.285-8.058H133.183v31.166H148.009c7.034 0 11.665-2.85 11.665-8.549Zm-8.548-13.312c0 2.315-1.915 3.295-4.942 3.295h-6.323v-6.59h6.768c2.894 0 4.497 1.158 4.497 3.206v.089Zm1.736 12.466c0 2.315-1.826 3.384-4.853 3.384h-8.148v-6.857h7.925c3.517 0 5.076 1.291 5.076 3.384v.089ZM200.996 38.186l-3.517-3.562c-2.671 2.493-5.12 3.84-8.413 3.84-6.59 0-11.354-5.232-11.354-12.176v-.089c0-6.944 4.675-12.176 11.354-12.176 3.206 0 5.832 1.291 8.325 3.74l2.495-4.541c-2.937-2.672-6.055-4.363-10.732-4.363-10.909 0-18.72 8.15-18.72 17.429v.089c0 9.368 7.81 17.429 18.72 17.429 4.586 0 7.879-1.747 10.82-4.452Z" fill="#fff" />
        </g>
      </g>
      <defs>
        <clipPath id="a">
          <path d="M0 0h319v56H0z" fill="#fff" />
        </clipPath>
      </defs>
    </svg>
  );

  // Blockchain-style diffused shapes - hexagons and glowing nodes
  const GeometricShapes = ({ intensity = 'normal' }: { intensity?: 'high' | 'normal' | 'low' }) => {
    const normalShapes = [
      { size: 200, left: 5,   top: 10,  type: 'hex',  color: 'rgba(240,185,11,0.12)' },
      { size: 120, left: 80,  top: 5,   type: 'node', color: 'rgba(240,185,11,0.15)' },
      { size: 280, left: 75,  top: 55,  type: 'hex',  color: 'rgba(255,255,255,0.06)' },
      { size: 100, left: 2,   top: 70,  type: 'node', color: 'rgba(240,185,11,0.10)' },
      { size: 160, left: 45,  top: 80,  type: 'blob', color: 'rgba(255,255,255,0.05)' },
    ];

    const lowShapes = [
      { size: 180, left: 85,  top: 8,   type: 'hex',  color: 'rgba(240,185,11,0.08)' },
      { size: 140, left: 5,   top: 55,  type: 'node', color: 'rgba(255,255,255,0.06)' },
      { size: 120, left: 50,  top: 75,  type: 'blob', color: 'rgba(240,185,11,0.06)' },
    ];

    const highShapes = [
      { size: 350, left: 65,  top: -10, type: 'hex',  color: 'rgba(240,185,11,0.18)' },
      { size: 250, left: -5,  top: 40,  type: 'hex',  color: 'rgba(240,185,11,0.14)' },
      { size: 180, left: 80,  top: 60,  type: 'node', color: 'rgba(240,185,11,0.20)' },
      { size: 140, left: 20,  top: 75,  type: 'node', color: 'rgba(255,255,255,0.12)' },
      { size: 300, left: 50,  top: 5,   type: 'blob', color: 'rgba(255,255,255,0.08)' },
      { size: 200, left: 10,  top: 10,  type: 'node', color: 'rgba(240,185,11,0.15)' },
      { size: 280, left: 70,  top: 80,  type: 'hex',  color: 'rgba(240,185,11,0.12)' },
      { size: 160, left: 35,  top: 50,  type: 'blob', color: 'rgba(255,255,255,0.06)' },
    ];

    const dataset = intensity === 'high' ? highShapes : intensity === 'low' ? lowShapes : normalShapes;

    return (
      <>
        {dataset.map((data, i) => {
          const className = data.type === 'hex'
            ? styles.hexagon
            : data.type === 'node'
              ? styles.node
              : styles.geometric;

          return (
            <div
              key={i}
              className={className}
              style={{
                width: `${data.size}px`,
                height: `${data.size}px`,
                left: `${data.left}%`,
                top: `${data.top}%`,
                backgroundColor: data.color,
                color: data.type === 'node' ? data.color : undefined,
              }}
            />
          );
        })}
      </>
    );
  };

  // Social Icon component
  const SocialIcon = ({ href, label, children }: { href: string; label: string; children: React.ReactNode }) => (
    <a href={href} target="_blank" rel="noopener noreferrer" title={label} className={styles.socialIcon}>
      {children}
    </a>
  );

  const slides = [
    // SLIDE 1 - COVER
    <div key="1" className={`${styles.slide} ${styles.coverSlide}`}>
      <GeometricShapes intensity="high" />
      <div className={styles.slideContent}>
        <div style={{textAlign:'center',marginBottom:'32px'}}>
          <img
            src="https://raw.githubusercontent.com/stefanocintioli-bot/bnb-chain-v0/main/logos/BNB_Chain_Symbol_Yellow.svg"
            alt="BNB Chain"
            style={{height:'96px',width:'auto',display:'inline-block'}}
          />
        </div>

        <h1 style={{ fontSize: 'clamp(2.8rem, 6vw, 5.5rem)', marginTop: '48px', color: 'var(--gold)', textAlign: 'center' }}>
          {c.s1_title}
        </h1>

        <p style={{ fontSize: 'clamp(0.85rem, 1.2vw, 1.1rem)', marginTop: '16px', textAlign: 'center', color: 'var(--text-muted)' }}>
          {c.s1_sub}
        </p>

        <div style={{ position: 'absolute', bottom: '24px', left: '24px' }}>
          <p style={{ fontFamily: 'var(--font-syne)', fontSize: 'clamp(0.8rem, 1vw, 1rem)', fontWeight: 700 }}>
            Stefano Cintioli
          </p>
          <p style={{ fontSize: '0.8rem', marginTop: '4px', color: 'var(--gold)' }}>
            {c.s1_role}
          </p>
        </div>
      </div>
    </div>,

    // SLIDE 2 - EL ECOSISTEMA BNB
    <div key="2" className={styles.slide}>
      <GeometricShapes intensity="low" />
      <div className={styles.slideContent}>
        <h2 style={{ fontSize: 'clamp(1.4rem, 3vw, 2rem)', marginBottom: '40px', fontFamily: 'var(--font-syne)', fontWeight: 700 }}>
          {c.s2_heading}
        </h2>

        <div className={styles.grid2x2}>
          {[
            { icon: '🟡', title: c.s2_c1t, desc: c.s2_c1d },
            { icon: '⚡', title: c.s2_c2t, desc: c.s2_c2d },
            { icon: '🗄️', title: c.s2_c3t, desc: c.s2_c3d },
            { icon: '🛡️', title: c.s2_c4t, desc: c.s2_c4d },
          ].map((item, i) => (
            <div key={i} className={styles.card}>
              <div style={{ fontSize: '2rem', marginBottom: '12px' }}>{item.icon}</div>
              <h3 style={{ fontSize: '1rem', fontFamily: 'var(--font-syne)', fontWeight: 700, marginBottom: '8px' }}>
                {item.title}
              </h3>
              <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>{item.desc}</p>
            </div>
          ))}
        </div>

        <p style={{ marginTop: '32px', textAlign: 'center', fontSize: '0.8rem', color: 'var(--gold)', letterSpacing: '0.1em' }}>
          {c.s2_foot}
        </p>
      </div>
    </div>,

    // SLIDE 3 - POR QUÉ BNB CHAIN
    <div key="3" className={styles.slide}>
      <GeometricShapes intensity="normal" />
      <div className={styles.slideContent}>
        <h2 style={{ fontSize: 'clamp(1.4rem, 3vw, 2rem)', marginBottom: '40px', fontFamily: 'var(--font-syne)', fontWeight: 700 }}>
          {c.s3_heading}
        </h2>

        <div className={styles.grid2x3}>
          {[
            { label: c.s3_l1, sub: c.s3_s1 },
            { label: c.s3_l2, sub: c.s3_s2 },
            { label: c.s3_l3, sub: c.s3_s3 },
            { label: c.s3_l4, sub: c.s3_s4 },
            { label: c.s3_l5, sub: c.s3_s5 },
            { label: c.s3_l6, sub: c.s3_s6 },
          ].map((stat, i) => (
            <div key={i} className={styles.statCard}>
              <p style={{ fontSize: '0.7rem', letterSpacing: '0.1em', color: 'var(--text-muted)', marginBottom: '8px' }}>
                {stat.label}
              </p>
              <p
                style={{
                  fontSize: 'clamp(1.8rem, 3.5vw, 3rem)',
                  fontFamily: 'var(--font-syne)',
                  fontWeight: 800,
                  color: 'var(--gold)',
                  fontVariantNumeric: 'tabular-nums',
                }}
              >
                {formatStat(i)}
              </p>
              <p style={{ fontSize: '0.75rem', marginTop: '4px', color: 'var(--gold)' }}>{stat.sub}</p>
            </div>
          ))}
        </div>
      </div>
    </div>,

    // SLIDE 4 - PARA EL DEVELOPER
    <div key="4" className={styles.slide}>
      <GeometricShapes intensity="normal" />
      <div className={styles.slideContent}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '60px', alignItems: 'center' }}>
          <div>
            <h2 style={{ fontSize: 'clamp(1.4rem, 2.5vw, 1.8rem)', marginBottom: '24px', fontFamily: 'var(--font-syne)', fontWeight: 700 }}>
              {c.s4_heading}
            </h2>
            <ul style={{ listStyle: 'none', gap: '16px', display: 'flex', flexDirection: 'column' }}>
              {[c.s4_b1, c.s4_b2, c.s4_b3].map(
                (item, i) => (
                  <li key={i} style={{ fontSize: '0.95rem', lineHeight: 1.8 }}>
                    • {item}
                  </li>
                )
              )}
            </ul>
          </div>
          <div style={{ textAlign: 'center' }}>
            <p
              style={{
                fontSize: 'clamp(1.5rem, 2.5vw, 2.2rem)',
                fontFamily: 'var(--font-syne)',
                fontWeight: 800,
                color: 'var(--gold)',
                lineHeight: 1.4,
              }}
            >
              {c.s4_stmt}
            </p>
            <p style={{ fontSize: '0.9rem', marginTop: '16px', color: 'var(--text-muted)' }}>
              {c.s4_sub}
            </p>
          </div>
        </div>
      </div>
    </div>,

    // SLIDE 5 - IA + WEB3
    <div key="5" className={styles.slide}>
      <GeometricShapes intensity="normal" />
      <div className={styles.slideContent}>
        <h2 style={{ fontSize: 'clamp(1.4rem, 3vw, 2rem)', marginBottom: '32px', fontFamily: 'var(--font-syne)', fontWeight: 700 }}>
          {c.s5_heading}
        </h2>

        <div style={{ background: 'rgba(240, 185, 11, 0.08)', borderLeft: '4px solid var(--gold)', padding: '16px 20px', borderRadius: '0 8px 8px 0', marginBottom: '32px' }}>
          <p style={{ fontSize: '0.9rem', lineHeight: 1.6 }}>
            {c.s5_hl}
          </p>
        </div>

        <div className={styles.grid1x3}>
          {[
            { title: c.s5_c1t, desc: c.s5_c1d },
            { title: c.s5_c2t, desc: c.s5_c2d },
            { title: c.s5_c3t, desc: c.s5_c3d },
          ].map((item, i) => (
            <div key={i} className={styles.card}>
              <h3 style={{ fontSize: '0.95rem', fontFamily: 'var(--font-syne)', fontWeight: 700, marginBottom: '8px' }}>
                {item.title}
              </h3>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>{item.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>,

    // SLIDE 6 - QUÉ PODÉS CONSTRUIR
    <div key="6" className={styles.slide}>
      <GeometricShapes intensity="normal" />
      <div className={styles.slideContent}>
        <h2 style={{ fontSize: 'clamp(1.4rem, 3vw, 2rem)', marginBottom: '40px', fontFamily: 'var(--font-syne)', fontWeight: 700 }}>
          {c.s6_heading}
        </h2>

        <div className={styles.grid1x3}>
          {[
            { emoji: '📈', title: c.s6_c1t, desc: c.s6_c1d },
            { emoji: '💬', title: c.s6_c2t, desc: c.s6_c2d },
            { emoji: '🤖', title: c.s6_c3t, desc: c.s6_c3d },
          ].map((item, i) => (
            <div key={i} className={styles.tallCard}>
              <div style={{ fontSize: '3rem', marginBottom: '16px' }}>{item.emoji}</div>
              <h3 style={{ fontSize: '1rem', fontFamily: 'var(--font-syne)', fontWeight: 700, marginBottom: '8px' }}>
                {item.title}
              </h3>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>{item.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>,

    // SLIDE 7 - PROGRAMAS DEL ECOSISTEMA
    <div key="7" className={styles.slide}>
      <GeometricShapes intensity="normal" />
      <div className={styles.slideContent}>
        <h2 style={{ fontSize: 'clamp(1.4rem, 3vw, 2rem)', marginBottom: '40px', fontFamily: 'var(--font-syne)', fontWeight: 700 }}>
          {c.s7_heading}
        </h2>

        <div className={styles.grid2x2}>
          {[
            { emoji: '🏆', title: c.s7_c1t, desc: c.s7_c1d },
            { emoji: '🔬', title: c.s7_c2t, desc: c.s7_c2d },
            { emoji: '🛠️', title: c.s7_c3t, desc: c.s7_c3d },
            { emoji: '💰', title: c.s7_c4t, desc: c.s7_c4d },
          ].map((item, i) => (
            <div key={i} className={styles.card}>
              <div style={{ fontSize: '2rem', marginBottom: '12px' }}>{item.emoji}</div>
              <h3 style={{ fontSize: '1rem', fontFamily: 'var(--font-syne)', fontWeight: 700, marginBottom: '8px' }}>
                {item.title}
              </h3>
              <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>{item.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>,

    // SLIDE 8 - LATAM COMMUNITY COLLAGE
    <div key="8" className={styles.slide}>
      <GeometricShapes intensity="normal" />
      <div className={styles.collageContainer}>
        <div className={styles.photoGrid}>
          <div className={styles.photoWrapper} style={{ gridArea: 'tl' }}>
            <img
              src="https://raw.githubusercontent.com/stefanocintioli-bot/bnb-chain-v0/main/events/crecimiento/Crecimiento%20Workshop.jpeg"
              alt="Crecimiento Workshop"
              loading="lazy"
              onError={(e) => {
                const target = e.target as HTMLImageElement;
                target.style.display = 'none';
              }}
            />
            <span className={styles.photoTag}>CRECIMIENTO WORKSHOP</span>
          </div>
          <div className={styles.photoWrapper} style={{ gridArea: 'tr' }}>
            <img
              src="https://raw.githubusercontent.com/stefanocintioli-bot/bnb-chain-v0/main/events/vendimia/Vendimia.jpg"
              alt="Vendimia Hackathon"
              loading="lazy"
              onError={(e) => {
                const target = e.target as HTMLImageElement;
                target.style.display = 'none';
              }}
            />
            <span className={styles.photoTag}>VENDIMIA HACKATHON</span>
          </div>
          <div className={styles.photoWrapper} style={{ gridArea: 'bl' }}>
            <img
              src="https://raw.githubusercontent.com/stefanocintioli-bot/bnb-chain-v0/main/events/university-tour/Univeersity%20Tour%20Groupal%20Photo.jpg"
              alt="University Tour"
              loading="lazy"
              onError={(e) => {
                const target = e.target as HTMLImageElement;
                target.style.display = 'none';
              }}
            />
            <span className={styles.photoTag}>UNIVERSITY TOUR</span>
          </div>
          <div className={styles.photoWrapper} style={{ gridArea: 'br' }}>
            <img
              src="https://raw.githubusercontent.com/stefanocintioli-bot/bnb-chain-v0/main/events/vendimia/Vendimia%20Buidlers.jpg"
              alt="Community Building"
              loading="lazy"
              onError={(e) => {
                const target = e.target as HTMLImageElement;
                target.style.display = 'none';
              }}
            />
            <span className={styles.photoTag}>COMMUNITY BUILDING</span>
          </div>
        </div>

        <h2 style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', textAlign: 'center', fontSize: 'clamp(1.8rem, 4vw, 3rem)', fontFamily: 'var(--font-syne)', fontWeight: 800, zIndex: 10, textShadow: '0 2px 20px rgba(0,0,0,0.8)', maxWidth: '500px' }}>
          {c.s8_title}
        </h2>
      </div>
    </div>,

    // SLIDE 9 - CRECIMIENTO POP UP
    <div key="9" className={styles.slide}>
      <GeometricShapes intensity="normal" />
      <div className={styles.slideContent}>
        <div style={{ display: 'grid', gridTemplateColumns: '60% 40%', gap: '40px', alignItems: 'center' }}>
          <div>
            <span className={styles.goldPill}>{c.s9_pill}</span>
            <h2 style={{ fontSize: 'clamp(1.4rem, 2.5vw, 1.9rem)', marginTop: '16px', marginBottom: '16px', fontFamily: 'var(--font-syne)', fontWeight: 700 }}>
              {c.s9_title}
            </h2>
            <p style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontFamily: 'var(--font-syne)', fontWeight: 800, color: 'var(--gold)', marginTop: '16px' }}>
              {c.s9_stat}
            </p>
            <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginTop: '8px' }}>
              {c.s9_sub}
            </p>
          </div>
          <div style={{ borderRadius: '12px', overflow: 'hidden', height: '400px' }}>
            <img
              src="https://raw.githubusercontent.com/stefanocintioli-bot/bnb-chain-v0/main/events/crecimiento/Crecimiento%20Workshop.jpeg"
              alt="Crecimiento Workshop"
              loading="lazy"
              style={{ width: '100%', height: '100%', objectFit: 'cover' }}
              onError={(e) => {
                const target = e.target as HTMLImageElement;
                target.style.display = 'none';
              }}
            />
          </div>
        </div>
      </div>
    </div>,

    // SLIDE 10 - VENDIMIA HACKATHON
    <div key="10" className={styles.slide}>
      <GeometricShapes intensity="normal" />
      <div className={styles.slideContent}>
        <div style={{ display: 'grid', gridTemplateColumns: '60% 40%', gap: '40px', alignItems: 'center' }}>
          <div>
            <span className={styles.goldPill}>{c.s10_pill}</span>
            <h2 style={{ fontSize: 'clamp(1.4rem, 2.5vw, 1.9rem)', marginTop: '16px', marginBottom: '16px', fontFamily: 'var(--font-syne)', fontWeight: 700 }}>
              {c.s10_title}
            </h2>
            <p style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontFamily: 'var(--font-syne)', fontWeight: 800, color: 'var(--gold)', marginTop: '16px' }}>
              {c.s10_stat}
            </p>
            <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginTop: '8px' }}>
              {c.s10_sub}
            </p>
          </div>
          <div style={{ borderRadius: '12px', overflow: 'hidden', height: '400px' }}>
            <img
              src="https://raw.githubusercontent.com/stefanocintioli-bot/bnb-chain-v0/main/events/vendimia/Vendimia.jpg"
              alt="Vendimia Hackathon"
              loading="lazy"
              style={{ width: '100%', height: '100%', objectFit: 'cover' }}
              onError={(e) => {
                const target = e.target as HTMLImageElement;
                target.style.display = 'none';
              }}
            />
          </div>
        </div>
      </div>
    </div>,

    // SLIDE 11 - UNIVERSITY TOUR
    <div key="11" className={styles.slide}>
      <GeometricShapes intensity="normal" />
      <div className={styles.slideContent}>
        <div style={{ display: 'grid', gridTemplateColumns: '60% 40%', gap: '40px', alignItems: 'center' }}>
          <div>
            <span className={styles.goldPill}>{c.s11_pill}</span>
            <h2 style={{ fontSize: 'clamp(1.4rem, 2.5vw, 1.9rem)', marginTop: '16px', marginBottom: '16px', fontFamily: 'var(--font-syne)', fontWeight: 700 }}>
              {c.s11_title}
            </h2>
            <p style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontFamily: 'var(--font-syne)', fontWeight: 800, color: 'var(--gold)', marginTop: '16px' }}>
              {c.s11_stat}
            </p>
            <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginTop: '8px' }}>
              {c.s11_sub}
            </p>
          </div>
          <div style={{ borderRadius: '12px', overflow: 'hidden', height: '400px' }}>
            <img
              src="https://raw.githubusercontent.com/stefanocintioli-bot/bnb-chain-v0/main/events/university-tour/Univeersity%20Tour%20Groupal%20Photo.jpg"
              alt="University Tour"
              loading="lazy"
              style={{ width: '100%', height: '100%', objectFit: 'cover' }}
              onError={(e) => {
                const target = e.target as HTMLImageElement;
                target.style.display = 'none';
              }}
            />
          </div>
        </div>
      </div>
    </div>,

    // SLIDE 12 - RECURSOS
    <div key="12" className={styles.slide}>
      <GeometricShapes intensity="normal" />
      <div className={styles.slideContent}>
        <h2 style={{ fontSize: 'clamp(1.4rem, 3vw, 2rem)', marginBottom: '40px', fontFamily: 'var(--font-syne)', fontWeight: 700 }}>
          {c.s12_heading}
        </h2>

        <div className={styles.grid2x3}>
          {[
            { emoji: '🚰', title: c.s12_c1t, desc: c.s12_c1d, href: 'https://testnet.bnbchain.org/faucet-smart' },
            { emoji: '🔍', title: c.s12_c2t, desc: c.s12_c2d, href: 'https://testnet.bscscan.com' },
            { emoji: '📄', title: c.s12_c3t, desc: c.s12_c3d, href: 'https://docs.bnbchain.org' },
            { emoji: '🛠️', title: c.s12_c4t, desc: c.s12_c4d, href: 'https://docs.bnbchain.org/showcase/mcp/skills/' },
            { emoji: '🤖', title: c.s12_c5t, desc: c.s12_c5d, href: 'https://github.com/bnb-chain/bnbagent-sdk' },
            { emoji: '⛓️', title: c.s12_c6t, desc: c.s12_c6d, href: 'https://chainlist.org' },
          ].map((item, i) => (
            <a
              key={i}
              href={item.href}
              target="_blank"
              rel="noopener noreferrer"
              className={styles.resourceCard}
            >
              <div style={{ fontSize: '2rem', marginBottom: '12px' }}>{item.emoji}</div>
              <h3 style={{ fontSize: '0.95rem', fontFamily: 'var(--font-syne)', fontWeight: 700, marginBottom: '4px' }}>
                {item.title}
              </h3>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{item.desc}</p>
            </a>
          ))}
        </div>
      </div>
    </div>,

    // SLIDE 13 - BUILD N BUILD
    <div key="13" className={`${styles.slide} ${styles.ctaSlide}`}>
      <GeometricShapes intensity="high" />
      <div className={styles.slideContent} style={{ textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
        <h1 style={{ fontSize: 'clamp(3.5rem, 8vw, 7rem)', fontFamily: 'var(--font-syne)', fontWeight: 800, color: 'var(--gold)', whiteSpace: 'nowrap' }}>
          BUILD N BUILD
        </h1>
        <p style={{ fontSize: '1rem', letterSpacing: '0.25em', marginTop: '8px' }}>
          {c.s13_sub}
        </p>

        <img
          src="https://raw.githubusercontent.com/stefanocintioli-bot/bnb-chain-v0/main/events/QR/QR.png"
          alt="Seguinos en @BNBChainLatAM"
          loading="lazy"
          style={{ width: '200px', height: '200px', borderRadius: '8px', margin: '32px auto 12px auto', display: 'block' }}
          onError={(e) => {
            const target = e.target as HTMLImageElement;
            target.style.display = 'none';
          }}
        />

        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginTop: '12px' }}>
          {c.s13_qr}
        </p>

        <div className={styles.socialLinks}>
          <SocialIcon href="https://x.com/BNBChainLatAM" label="X">
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.744l7.73-8.835L1.254 2.25H8.08l4.259 5.631 5.905-5.631zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
            </svg>
          </SocialIcon>
          <SocialIcon href="https://t.me/BNBChainES" label="Telegram">
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z" />
            </svg>
          </SocialIcon>
          <SocialIcon href="https://discord.gg/bnbchain" label="Discord">
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M20.317 4.37a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.21.375-.444.864-.608 1.25a18.27 18.27 0 0 0-5.487 0 12.64 12.64 0 0 0-.617-1.25.077.077 0 0 0-.079-.037A19.736 19.736 0 0 0 3.677 4.37a.07.07 0 0 0-.032.027C.533 9.046-.32 13.58.099 18.057c.001.022.015.04.036.05a19.91 19.91 0 0 0 5.993 3.03.078.078 0 0 0 .084-.028c.462-.63.874-1.295 1.226-1.994a.076.076 0 0 0-.041-.106 13.107 13.107 0 0 1-1.872-.892.077.077 0 0 1-.008-.128 10.2 10.2 0 0 0 .372-.292.074.074 0 0 1 .077-.01c3.928 1.793 8.18 1.793 12.062 0a.074.074 0 0 1 .078.01c.12.098.246.198.373.292a.077.077 0 0 1-.006.127 12.299 12.299 0 0 1-1.873.892.077.077 0 0 0-.041.107c.36.698.772 1.362 1.225 1.993a.076.076 0 0 0 .084.028 19.839 19.839 0 0 0 6.002-3.03.077.077 0 0 0 .036-.05c.5-5.177-.838-9.674-3.549-13.66a.061.061 0 0 0-.031-.03z" />
            </svg>
          </SocialIcon>
          <SocialIcon href="https://docs.bnbchain.org" label="Docs">
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6zm-1 1.5L18.5 9H13V3.5zM6 20V4h5v7h7v9H6z" />
            </svg>
          </SocialIcon>
        </div>
      </div>
    </div>,
  ];

  return (
    <div className={styles.presentationContainer} onTouchStart={handleTouchStart} onTouchEnd={handleTouchEnd}>
      {/* Language Toggle */}
      <div style={{position:'absolute',top:'24px',right:'24px',zIndex:100,display:'flex',gap:'4px'}}>
        {(['en','es','pt'] as const).map((l) => (
          <button
            key={l}
            onClick={() => setLang(l)}
            style={{
              padding:'4px 10px',
              borderRadius:'4px',
              border: lang === l ? '1px solid #F0B90B' : '1px solid rgba(255,255,255,0.2)',
              background: lang === l ? '#F0B90B' : 'transparent',
              color: lang === l ? '#0D0D0D' : '#888888',
              fontFamily:'var(--font-dm-mono)',
              fontSize:'0.7rem',
              fontWeight:500,
              letterSpacing:'0.05em',
              cursor:'pointer',
              textTransform:'uppercase',
              transition:'all 150ms ease',
            }}
          >
            {l}
          </button>
        ))}
      </div>

      {/* Render all slides */}
      <div className={styles.slidesWrapper}>
        {slides.map((slide, i) => (
          <div
            key={i}
            className={styles.slideContainer}
            style={{
              opacity: i === currentSlide ? 1 : 0,
              pointerEvents: i === currentSlide ? 'auto' : 'none',
              transform: `translateX(${(i - currentSlide) * 100}%)`,
            }}
          >
            {slide}
          </div>
        ))}
      </div>

      {/* Logo */}
      <div style={{position:'absolute',top:'24px',left:'24px',zIndex:50}}>
        <img
          src="https://raw.githubusercontent.com/stefanocintioli-bot/bnb-chain-v0/main/logos/BNB_Chain_Logo_White.svg"
          alt="BNB Chain"
          style={{height:'20px',width:'auto',display:'block'}}
        />
      </div>

      {/* Watermark */}
      <div className={styles.watermark}>BUILD WEB3 WITH BNB CHAIN</div>

      {/* Slide Counter */}
      <div className={styles.slideCounter}>
        {String(currentSlide + 1).padStart(2, '0')} / 13
      </div>

      {/* Progress Bar */}
      <div
        className={styles.progressBar}
        style={{ width: `${progressPercentage}%` }}
      />
    </div>
  );
};

export default BNBChainPresentation;
